# Generated by Django 4.2.5 on 2023-09-28 02:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='fields',
            new_name='questions_fields',
        ),
    ]
